sudo: false

language: go

git:
  depth: 1

install: go get -v github.com/spf13/hugo

script:
  - hugo
  - pwd
  - ls
  - ls public

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $api_key
  on:
    branch: master
  local_dir: public
  repo: Yihy/yihy.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot