sudo: required

language: go

git:
  depth: 1
  submodules: true
#before_install:
#  - git submodule update --init --recursive
#  - git submodule foreach git checkout master
#  - git submodule foreach git pull

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.tar.gz
  - tar xzf  hugo_0.52_Linux-64bit.tar.gz hugo
  - chmod a+x hugo
  - sudo apt-get install -y tree

script:

#  - mkdir themes
#  - cd ./themes
#  - wget https://github.com/Yihy/hugo-minimalist-theme.git
#  - cd ../
  - tree
  - ./hugo
  - cp -f CNAME public/

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $api_key
  on:
    branch: master
  local_dir: public
  repo: Yihy/yihy.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot