sudo: required

language: go

git:
  depth: 1
  submodules: false
before_install:
  - git submodule update --init --recursive

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31.1/hugo_0.31.1_Linux-64bit.tar.gz
  - tar xzf  hugo_0.31.1_Linux-64bit.tar.gz hugo
  - chmod a+x hugo
  - sudo apt-get install -y tree

script:

#  - mkdir themes
#  - cd ./themes
#  - wget https://github.com/Yihy/hugo-minimalist-theme.git
#  - cd ../
  - tree
  - ./hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $api_key
  on:
    branch: master
  local_dir: public
  repo: Yihy/yihy.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot