---
baseurl:  http://icoding.pro/
title: 念去去云
languageCode: zh-cn
#languageCode: en-us

# Define how many pages appear per site
paginate: 10
# Enable comments powered by Disqus by entering your disqus shortname
disqusShortname : 2150968
# Enable gogle analytics by entering your tracking code
googleAnalytics :
theme : hugo-minimalist-theme
params:
  site_author : Yihy
  site_description : 博客
  location : BeiJing
  # Link custom assets relative to /static
  avatar : https://avatars0.githubusercontent.com/u/18240360?s=40&v=4
  header_background: img/desk.jpg
  header_title : 念去去云
  copyright: Powered by [Hugo](http://gohugo.io).
  custom_css : []
  custom_js  : []
social:
    # Add your social network accounts to the profile section on the left
    # by entering your username. The links to your account will be
    # create automatically.
  twitter : "spf13"
  facebook:
  linkedin  :
  behance   :
  dribbble  :
  instagram :
  github : Yihy
  gplus :

---
